CREATE OR REPLACE TRIGGER STAROST_IRVASA
	BEFORE INSERT OR UPDATE
	ON IRVAS
	REFERENCING NEW AS NEW
	FOR EACH ROW
DECLARE
trenutna_godina NUMBER;
godina_rodjenja NUMBER;
BEGIN
	trenutna_godina := EXTRACT(YEAR FROM SYSDATE);
	godina_rodjenja := EXTRACT(YEAR FROM :NEW.Datum_rodjenja);
	SELECT trenutna_godina - godina_rodjenja INTO :NEW.Starost FROM DUAL;
END;
/
ALTER TRIGGER STAROST_IRVASA ENABLE;



CREATE OR REPLACE TRIGGER STAROST_IRVASA
	BEFORE INSERT OR UPDATE
	ON IRVAS
	REFERENCING NEW AS NEW
	FOR EACH ROW
DECLARE
trenutna_godina NUMBER;
godina_rodjenja NUMBER;
starost NUMBER;
BEGIN
	trenutna_godina := EXTRACT(YEAR FROM SYSDATE);
	godina_rodjenja := EXTRACT(YEAR FROM :NEW.Datum_rodjenja);
	starost := trenutna_godina - godina_rodjenja;
	IF (EXTRACT(MONTH FROM SYSDATE) < EXTRACT(MONTH FROM :NEW.Datum_rodjenja)) THEN
		starost := starost - 1;
	ELSIF (EXTRACT(MONTH FROM SYSDATE) = EXTRACT(MONTH FROM :NEW.Datum_rodjenja)) THEN
		IF (EXTRACT(DAY FROM SYSDATE) < EXTRACT(DAY FROM :NEW.Datum_rodjenja)) THEN
			starost := starost - 1;
		END IF;
	END IF;
	SELECT starost INTO :NEW.Starost FROM DUAL;
END;
/
ALTER TRIGGER STAROST_IRVASA ENABLE;

--iz nekog razloga vrti beskonacno?

CREATE OR REPLACE TRIGGER BROJ_VILENJAKA_U_DELU_RADIONICE
	BEFORE INSERT OR UPDATE
	ON VILENJAK
	REFERENCING NEW AS NEW
	FOR EACH ROW
BEGIN
UPDATE DEO_RADIONICE
SET Broj_angazovanih_vilenjaka = Broj_angazovanih_vilenjaka + 1
WHERE DEO_RADIONICE.ID = :NEW.ID_Dela_radionice;
END;
/
ALTER TRIGGER BROJ_VILENJAKA_U_DELU_RADIONICE ENABLE;