 --RESETOVANJE SHEME
	DROP TABLE DETE CASCADE CONSTRAINTS;
	DROP TABLE PISMO CASCADE CONSTRAINTS;
	DROP TABLE IGRACKA CASCADE CONSTRAINTS;
	DROP TABLE LISTA_ZELJA CASCADE CONSTRAINTS;
	DROP TABLE POKLON CASCADE CONSTRAINTS;
	DROP TABLE VILENJAK_ZA_IRVASE CASCADE CONSTRAINTS;
	DROP TABLE VILENJAK_ZA_ISPORUKU_POKLONA CASCADE CONSTRAINTS;
	DROP TABLE VILENJAK_ZA_POKLON CASCADE CONSTRAINTS;
	DROP TABLE VILENJAK_ZA_IZRADU_IGRACAKA CASCADE CONSTRAINTS;
	DROP TABLE TIM CASCADE CONSTRAINTS;
	DROP TABLE DEO_RADIONICE CASCADE CONSTRAINTS;
	DROP TABLE MAGICNA_VESTINA CASCADE CONSTRAINTS;
	DROP TABLE TOVAR CASCADE CONSTRAINTS;
	DROP TABLE IRVAS CASCADE CONSTRAINTS;
	DROP TABLE ZA_IRVASE_POSEDUJE_VESTINU CASCADE CONSTRAINTS;
	DROP TABLE ZA_ISPORUKU_POSEDUJE_VESTINU CASCADE CONSTRAINTS;
	DROP TABLE ZA_IGRACKE_POSEDUJE_VESTINU CASCADE CONSTRAINTS;
	DROP TABLE ZA_POKLON_POSEDUJE_VESTINU CASCADE CONSTRAINTS;
	DROP TABLE DETE_RODITELJ CASCADE CONSTRAINTS;
	DROP TABLE IRVAS_ISPORUCUJE_TOVAR CASCADE CONSTRAINTS;
	DROP TABLE PAKOVANJE_POKLONA CASCADE CONSTRAINTS;
	DROP TABLE PESMA CASCADE CONSTRAINTS;
	
	DROP SEQUENCE DETE_PK_SEQ;
	DROP SEQUENCE PISMO_PK_SEQ;
	DROP SEQUENCE LISTA_ZELJA_PK_SEQ;
	DROP SEQUENCE IGRACKA_PK_SEQ;
	DROP SEQUENCE PESMA_PK_SEQ;
	DROP SEQUENCE TIM_PK_SEQ;
	DROP SEQUENCE POKLON_PK_SEQ;
	DROP SEQUENCE TOVAR_PK_SEQ;
	DROP SEQUENCE IRVAS_PK_SEQ;
	DROP SEQUENCE VILENJAK_ZA_IRVASE_PK_SEQ;
	DROP SEQUENCE VILENJAK_ZA_ISPORUKU_PK_SEQ;
	DROP SEQUENCE VILENJAK_ZA_IGRACKE_PK_SEQ;
	DROP SEQUENCE VILENJAK_ZA_POKLON_PK_SEQ;

	DROP SEQUENCE DEO_RADIONICE_PK_SEQ;
	DROP SEQUENCE MAGICNA_VESTINA_PK_SEQ;
	DROP SEQUENCE DETE_RODITELJ_PK_SEQ;
	DROP SEQUENCE ZA_IRVASE_VESTINA_PK_SEQ;
	DROP SEQUENCE ZA_ISPORUKU_VESTINA_PK_SEQ;
	DROP SEQUENCE ZA_IGRACKE_VESTINA_PK_SEQ;
	DROP SEQUENCE ZA_POKLON_VESTINA_PK_SEQ;
	DROP SEQUENCE PAKOVANJE_POKLONA_PK_SEQ;
	DROP SEQUENCE IRVAS_TOVAR_PK_SEQ;
	
	DROP TRIGGER DETE_PK_AUTO;
	DROP TRIGGER PISMO_PK_AUTO;
	DROP TRIGGER LISTA_ZELJA_PK_AUTO;
	DROP TRIGGER IGRACKA_PK_AUTO;
	DROP TRIGGER PESMA_PK_AUTO;
	DROP TRIGGER TIM_PK_AUTO;
	DROP TRIGGER POKLON_PK_AUTO;
	DROP TRIGGER TOVAR_PK_AUTO;
	DROP TRIGGER IRVAS_PK_AUTO;
	DROP TRIGGER DEO_RADIONICE_PK_AUTO;
	DROP TRIGGER MAGICNA_VESTINA_PK_AUTO;
	DROP TRIGGER ZA_IRVASE_PK_AUTO;
	DROP TRIGGER ZA_ISPORUKU_PK_AUTO;
	DROP TRIGGER ZA_IGRACKE_PK_AUTO;
	DROP TRIGGER ZA_POKLON_PK_AUTO;

	DROP TRIGGER IRVAS_TOVAR_PK_AUTO;
	DROP TRIGGER PAKOVANJE_POKLONA_PK_AUTO;
	DROP TRIGGER ZA_IRVASE_VESTINA_PK_AUTO;
	DROP TRIGGER ZA_ISPORUKU_VESTINA_PK_SEQ;
	DROP TRIGGER ZA_IGRACKE_VESTINA_PK_AUTO;
	DROP TRIGGER ZA_POKLON_VESTINA_PK_AUTO;
	DROP TRIGGER DETE_RODITELJ_PK_AUTO;

	
	
	
--KREIRANJE SEKVENCI
	CREATE SEQUENCE DETE_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE PISMO_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE LISTA_ZELJA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE IGRACKA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE PESMA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE TIM_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE POKLON_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE TOVAR_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE IRVAS_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE DEO_RADIONICE_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE VILENJAK_ZA_IRVASE_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE VILENJAK_ZA_ISPORUKU_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE VILENJAK_ZA_IGRACKE_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE VILENJAK_ZA_POKLON_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	CREATE SEQUENCE MAGICNA_VESTINA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	
	  CREATE SEQUENCE IRVAS_TOVAR_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE PAKOVANJE_POKLONA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE ZA_IRVASE_VESTINA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE ZA_ISPORUKU_VESTINA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE ZA_IGRACKE_VESTINA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE ZA_POKLON_VESTINA_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	  CREATE SEQUENCE DETE_RODITELJ_PK_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
	
--KREIRANJE TABELA
	CREATE TABLE DETE 
	(
		 ID NUMBER(10),
		 Ime VARCHAR2(30) NOT NULL,
		 Prezime VARCHAR2(30) NOT NULL,
		 Drzava VARCHAR2(30),
		 Grad VARCHAR2(30),
		 Adresa VARCHAR2(50),
		 Datum_rodjenja DATE NOT NULL
	);

	CREATE TABLE PISMO
	(
		ID NUMBER(10),
		Tekst VARCHAR2(1500) NOT NULL,
		Indeks_dobrote NUMBER(4,2) NOT NULL,
		ID_Deteta NUMBER(10),
		Datum_slanja DATE NOT NULL,
		Datum_prijema DATE NOT NULL	
	);

	CREATE TABLE LISTA_ZELJA
	(
		ID NUMBER(10),
		ID_Pisma NUMBER(10) NOT NULL
	);

	CREATE TABLE IGRACKA 
	(
		ID NUMBER(10),
		ID_Liste_zelja NUMBER(10) NOT NULL,
		Redni_broj NUMBER(5) NOT NULL,
		Tip VARCHAR2(50) NOT NULL,
		Opis VARCHAR2(150),
		ID_Poklona NUMBER(10),
		ID_Vilenjaka_za_igracke NUMBER(10),
		ID_Dela_radionice NUMBER(10)
		
	);

	CREATE TABLE PESMA
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_irvase NUMBER(10) NOT NULL,
		Naziv VARCHAR2(50) NOT NULL,  
		Tekst VARCHAR2(2000) NOT NULL
	);

	CREATE TABLE TIM
	(
		ID NUMBER(10),
		Naziv VARCHAR2(20)
	);

	CREATE TABLE POKLON 
	(
		ID NUMBER(10),
		Boja VARCHAR2(25),
		Posveta VARCHAR2(250),
		ID_Liste_zelja NUMBER(10),
		ID_Tovara NUMBER(10)
	);

	CREATE TABLE TOVAR
	(
		ID NUMBER(10),
		Grad VARCHAR2(50) NOT NULL
	);

	CREATE TABLE IRVAS
	(
		ID NUMBER(10),
		Ime VARCHAR2(50) UNIQUE NOT NULL,
		Nadimak VARCHAR2(50) UNIQUE NOT NULL,
		Pol CHAR(1) CHECK (POL IN ('M', 'Z')),
		Datum_rodjenja DATE
	);

	CREATE TABLE DEO_RADIONICE 
	(
		ID NUMBER(10),
		Naziv VARCHAR2(20),
		Tip_igracke VARCHAR2(50)
	);

	CREATE TABLE MAGICNA_VESTINA
	(
		ID NUMBER(10),
		Naziv VARCHAR2(20) NOT NULL UNIQUE,
		ID_Dela_radionice NUMBER(10)
	);
	
	CREATE TABLE VILENJAK_ZA_IRVASE 
	(
		ID NUMBER(10),
		Ime VARCHAR2(30) UNIQUE NOT NULL,
		Zemlja_porekla VARCHAR2(30) NOT NULL,
		Datum_zaposljavanja DATE NOT NULL,
		ID_Irvasa NUMBER(10)
		
	);
	
	CREATE TABLE VILENJAK_ZA_ISPORUKU_POKLONA
	(
		ID NUMBER(10),
		Ime VARCHAR2(30) UNIQUE NOT NULL,
		Zemlja_porekla VARCHAR2(30) NOT NULL,
		Datum_zaposljavanja DATE NOT NULL,
		ID_Tovara NUMBER(10)
	);
	
	CREATE TABLE VILENJAK_ZA_POKLON
	(
		ID NUMBER(10),
		Ime VARCHAR2(30) UNIQUE NOT NULL,
		Zemlja_porekla VARCHAR2(30) NOT NULL,
		Datum_zaposljavanja DATE NOT NULL
	);
	
	CREATE TABLE VILENJAK_ZA_IZRADU_IGRACAKA
	(	
		ID NUMBER(10),
		Ime VARCHAR2(30) UNIQUE NOT NULL,
		Zemlja_porekla VARCHAR2(30) NOT NULL,
		Datum_zaposljavanja DATE NOT NULL,
		Tip_materijala VARCHAR2(50),
		Flag_koordinator NUMBER(1) CHECK (Flag_koordinator IN (0, 1)),
		ID_Tima NUMBER(10),
		Flag_sef NUMBER(1) CHECK (Flag_sef IN (0, 1)),
		Datum_postavljanja DATE ,
		ID_Dela_radionice NUMBER(10),
		ID_Mentora NUMBER(10),
		Ocena NUMBER(2) CHECK (Ocena BETWEEN 1 AND 10), 
		Duzina_obuke NUMBER(5)
		
	);
	
	CREATE TABLE IRVAS_ISPORUCUJE_TOVAR
	(
		ID NUMBER(10), 
		ID_Irvasa NUMBER(10) NOT NULL,
		ID_Tovara NUMBER(10) NOT NULL
	);

	CREATE TABLE PAKOVANJE_POKLONA
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_poklone NUMBER(10) NOT NULL,
		ID_Poklona NUMBER(10) NOT NULL
	);

	CREATE TABLE ZA_IRVASE_POSEDUJE_VESTINU
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_irvase NUMBER(10) NOT NULL,
		ID_Vestine NUMBER(10) NOT NULL
	);
	
	CREATE TABLE ZA_ISPORUKU_POSEDUJE_VESTINU
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_tovar NUMBER(10) NOT NULL,
		ID_Vestine NUMBER(10) NOT NULL
	);

	CREATE TABLE ZA_POKLON_POSEDUJE_VESTINU
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_poklone NUMBER(10) NOT NULL,
		ID_Vestine NUMBER(10) NOT NULL
	);
	
	CREATE TABLE ZA_IGRACKE_POSEDUJE_VESTINU
	(
		ID NUMBER(10),
		ID_Vilenjaka_za_igracke NUMBER(10) NOT NULL,
		ID_Vestine NUMBER(10) NOT NULL
	);
	
	CREATE TABLE DETE_RODITELJ
	(
		ID NUMBER(10),
		ID_Deteta NUMBER(10) NOT NULL,
		Ime_roditelja VARCHAR2(50)
	);
	

	
--KREIRANJE INDEKSA
	CREATE UNIQUE INDEX DETE_PK ON DETE(ID);
	CREATE UNIQUE INDEX PISMO_PK ON PISMO(ID);
	CREATE UNIQUE INDEX LISTA_ZELJA_PK ON LISTA_ZELJA(ID);
	CREATE UNIQUE INDEX IGRACKA_PK ON IGRACKA(ID);
	CREATE UNIQUE INDEX PESMA_PK ON PESMA(ID);
	CREATE UNIQUE INDEX TIM_PK ON TIM(ID);
	CREATE UNIQUE INDEX POKLON_PK ON POKLON(ID);
	CREATE UNIQUE INDEX TOVAR_PK ON TOVAR(ID);
	CREATE UNIQUE INDEX IRVAS_PK ON IRVAS(ID);
	CREATE UNIQUE INDEX DEO_RADIONICE_PK ON DEO_RADIONICE(ID);
	CREATE UNIQUE INDEX VILENJAK_ZA_IRVASE_PK ON VILENJAK_ZA_IRVASE(ID);
	CREATE UNIQUE INDEX VILENJAK_ZA_ISPORUKU_PK ON VILENJAK_ZA_ISPORUKU_POKLONA(ID);
	CREATE UNIQUE INDEX VILENJAK_ZA_IGRACKE_PK ON VILENJAK_ZA_IZRADU_IGRACAKA(ID);
	CREATE UNIQUE INDEX VILENJAK_ZA_POKLON_PK ON VILENJAK_ZA_POKLON(ID);
	CREATE UNIQUE INDEX MAGICNA_VESTINA_PK ON MAGICNA_VESTINA(ID);
	CREATE UNIQUE INDEX IRVAS_ISPORUCUJE_TOVAR_PK_PK ON IRVAS_ISPORUCUJE_TOVAR(ID);
	CREATE UNIQUE INDEX PAKOVANJE_POKLONA_PK ON PAKOVANJE_POKLONA(ID);
	CREATE UNIQUE INDEX ZA_IRVASE_POSEDUJE_VESTINU_PK ON ZA_IRVASE_POSEDUJE_VESTINU(ID);
	CREATE UNIQUE INDEX ZA_ISPOR_POSEDUJE_VESTINU_PK ON ZA_ISPORUKU_POSEDUJE_VESTINU(ID);
	CREATE UNIQUE INDEX ZA_IGRACKE_POSEDUJE_VESTINU_PK ON ZA_IGRACKE_POSEDUJE_VESTINU(ID);
	CREATE UNIQUE INDEX ZA_POKLON_POSEDUJE_VESTINU_PK ON ZA_POKLON_POSEDUJE_VESTINU(ID);
	CREATE UNIQUE INDEX DETE_RODITELJ_PK ON DETE_RODITELJ(ID);
	

--KREIRANJE OGRANICENJA PRIMARNOG KLJUCA
	ALTER TABLE DETE ADD CONSTRAINT DETE_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE PISMO ADD CONSTRAINT PISMO_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE LISTA_ZELJA ADD CONSTRAINT LISTA_ZELJA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE PESMA ADD CONSTRAINT PESMA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE TIM ADD CONSTRAINT TIM_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE POKLON ADD CONSTRAINT POKLON_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE TOVAR ADD CONSTRAINT TOVAR_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE IRVAS ADD CONSTRAINT IRVAS_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE DETE_RODITELJ ADD CONSTRAINT DETE_RODITELJ_PK PRIMARY KEY (ID)ENABLE;
	ALTER TABLE DEO_RADIONICE ADD CONSTRAINT DEO_RADIONICE_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE MAGICNA_VESTINA ADD CONSTRAINT MAGICNA_VESTINA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_IRVASE ADD CONSTRAINT VILENJAK_ZA_IRVASE_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_ISPORUKU_POKLONA ADD CONSTRAINT VILENJAK_ZA_ISPOR_POKLONA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_IZRADU_IGRACAKA ADD CONSTRAINT VILENJAK_ZA_IZRADU_IGRACAKA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_POKLON ADD CONSTRAINT VILENJAK_ZA_POKLON_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE IRVAS_ISPORUCUJE_TOVAR ADD CONSTRAINT IRVAS_ISPORUCUJE_TOVAR_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE PAKOVANJE_POKLONA ADD CONSTRAINT PAKOVANJE_POKLONA_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE ZA_IRVASE_POSEDUJE_VESTINU ADD CONSTRAINT ZA_IRVASE_POSEDUJE_VESTINU_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE ZA_ISPORUKU_POSEDUJE_VESTINU ADD CONSTRAINT ZA_ISPOR_POSED_VESTINU_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE ZA_IGRACKE_POSEDUJE_VESTINU ADD CONSTRAINT ZA_IGRACKE_POSEDUJE_VESTINU_PK PRIMARY KEY (ID) ENABLE;
	ALTER TABLE ZA_POKLON_POSEDUJE_VESTINU ADD CONSTRAINT ZA_POKLON_POSEDUJE_VESTINU_PK PRIMARY KEY (ID) ENABLE;

--DODAVANJE OGRANICENJA SPOLJASNJEG KLJUCA I OGRANICENJA UNIQUE ZA KLJUCEVE KANDIDATE PO PRAVILIMA PREVODJENJA
	ALTER TABLE PISMO ADD CONSTRAINT PISMO_DETE_FK FOREIGN KEY (ID_Deteta) REFERENCES DETE(ID) ENABLE;
	
	ALTER TABLE LISTA_ZELJA ADD CONSTRAINT ZELJE_PISMO_FK FOREIGN KEY (ID_Pisma) REFERENCES PISMO(ID) ENABLE;

	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_UNIQUE UNIQUE (ID_Liste_zelja, Redni_broj) ENABLE;
	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_LISTA_FK FOREIGN KEY (ID_Liste_zelja) REFERENCES LISTA_ZELJA(ID) ENABLE;
	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_POKLON_FK FOREIGN KEY (ID_Poklona) REFERENCES POKLON(ID) ENABLE;
	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_VILENJAK_FK FOREIGN KEY (ID_Vilenjaka_za_igracke) REFERENCES VILENJAK_ZA_IZRADU_IGRACAKA(ID) ENABLE;
	ALTER TABLE IGRACKA ADD CONSTRAINT IGRACKA_DEO_RADIONICE_FK FOREIGN KEY (ID_Dela_radionice) REFERENCES DEO_RADIONICE(ID) ENABLE;

	ALTER TABLE PESMA ADD CONSTRAINT PESMA_UNIQUE UNIQUE (ID_Vilenjaka_za_irvase, Naziv) ENABLE;
	ALTER TABLE PESMA ADD CONSTRAINT PESMA_VILENJAK_FK FOREIGN KEY (ID_Vilenjaka_za_irvase) REFERENCES VILENJAK_ZA_IRVASE(ID) ENABLE;

	ALTER TABLE TIM ADD CONSTRAINT TIM_UNIQUE UNIQUE (Naziv) ENABLE;

	ALTER TABLE POKLON ADD CONSTRAINT POKLON_LISTA_FK FOREIGN KEY (ID_Liste_zelja) REFERENCES LISTA_ZELJA(ID) ENABLE;
	ALTER TABLE POKLON ADD CONSTRAINT POKLON_TOVAR_FK FOREIGN KEY (ID_Tovara) REFERENCES TOVAR(ID) ENABLE;

	ALTER TABLE MAGICNA_VESTINA ADD CONSTRAINT MAGICNA_RADIONICA_FK FOREIGN KEY (ID_Dela_radionice) REFERENCES DEO_RADIONICE(ID) ENABLE;

	ALTER TABLE VILENJAK_ZA_IZRADU_IGRACAKA ADD CONSTRAINT VILENJAK_TIM_FK FOREIGN KEY (ID_Tima) REFERENCES TIM(ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_IZRADU_IGRACAKA ADD CONSTRAINT VILENJAK_DEO_RADIONICE_FK FOREIGN KEY (ID_Dela_radionice) REFERENCES DEO_RADIONICE(ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_IZRADU_IGRACAKA ADD CONSTRAINT VILENJAK_MENTOR_FK FOREIGN KEY (ID_Mentora) REFERENCES VILENJAK_ZA_IZRADU_IGRACAKA(ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_IRVASE ADD CONSTRAINT VILENJAK_IRVAS_FK FOREIGN KEY (ID_Irvasa) REFERENCES IRVAS(ID) ENABLE;
	ALTER TABLE VILENJAK_ZA_ISPORUKU_POKLONA ADD CONSTRAINT VILENJAK_TOVAR_FK FOREIGN KEY (ID_Tovara) REFERENCES TOVAR(ID) ENABLE;

	ALTER TABLE IRVAS_ISPORUCUJE_TOVAR ADD CONSTRAINT ISPORUKA_IRVAS_FK FOREIGN KEY (ID_Irvasa) REFERENCES IRVAS(ID) ENABLE;
	ALTER TABLE IRVAS_ISPORUCUJE_TOVAR ADD CONSTRAINT ISPORUKA_TOVAR_FK FOREIGN KEY (ID_Tovara) REFERENCES TOVAR(ID) ENABLE;
	ALTER TABLE IRVAS_ISPORUCUJE_TOVAR ADD CONSTRAINT IRVAS_TOVAR_UNIQE UNIQUE (ID_Irvasa, ID_Tovara) ENABLE;

	ALTER TABLE PAKOVANJE_POKLONA ADD CONSTRAINT PAKOVANJE_POKLONA_VILENJAK_FK FOREIGN KEY (ID_Vilenjaka_za_poklone) REFERENCES VILENJAK_ZA_POKLON(ID) ENABLE;
	ALTER TABLE PAKOVANJE_POKLONA ADD CONSTRAINT PAKOVANJE_POKLONA_POKLON_FK FOREIGN KEY (ID_Poklona) REFERENCES POKLON(ID) ENABLE;
	ALTER TABLE PAKOVANJE_POKLONA ADD CONSTRAINT PAKOVANJE_POKLONA_UNIQE UNIQUE (ID_Vilenjaka_za_poklone, ID_Poklona) ENABLE;

	ALTER TABLE ZA_IRVASE_POSEDUJE_VESTINU ADD CONSTRAINT ZA_IRVASE_VESTINA_FK FOREIGN KEY (ID_Vestine) REFERENCES MAGICNA_VESTINA(ID) ENABLE;
	ALTER TABLE ZA_IRVASE_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_VILENJAK_ZA_IRVASE_FK FOREIGN KEY (ID_Vilenjaka_za_irvase) REFERENCES VILENJAK_ZA_IRVASE(ID) ENABLE;
	ALTER TABLE ZA_IRVASE_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_IRVAS_UNIQUE UNIQUE (ID_Vilenjaka_za_irvase, ID_Vestine) ENABLE;
	
	ALTER TABLE ZA_ISPORUKU_POSEDUJE_VESTINU ADD CONSTRAINT ZA_ISPORUKU_VESTINA_FK FOREIGN KEY (ID_Vestine) REFERENCES MAGICNA_VESTINA(ID) ENABLE;
	ALTER TABLE ZA_ISPORUKU_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_VILENJAK_ZA_ISPOR_FK FOREIGN KEY (ID_Vilenjaka_za_tovar) REFERENCES VILENJAK_ZA_ISPORUKU_POKLONA(ID) ENABLE;
	ALTER TABLE ZA_ISPORUKU_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_TOVAR_UNIQUE UNIQUE (ID_Vilenjaka_za_tovar, ID_Vestine) ENABLE;
	
	ALTER TABLE ZA_IGRACKE_POSEDUJE_VESTINU ADD CONSTRAINT ZA_IGRACKE_VESTINA_FK FOREIGN KEY (ID_Vestine) REFERENCES MAGICNA_VESTINA(ID) ENABLE;
	ALTER TABLE ZA_IGRACKE_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_VILENJAK_ZA_IGRACKE_FK FOREIGN KEY (ID_Vilenjaka_za_igracke) REFERENCES VILENJAK_ZA_IZRADU_IGRACAKA(ID) ENABLE;
	ALTER TABLE ZA_IGRACKE_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_IGRACKA_UNIQUE UNIQUE (ID_Vilenjaka_za_igracke, ID_Vestine) ENABLE;
	
	ALTER TABLE ZA_POKLON_POSEDUJE_VESTINU ADD CONSTRAINT ZA_POKLON_VESTINA_FK FOREIGN KEY (ID_Vestine) REFERENCES MAGICNA_VESTINA(ID) ENABLE;
	ALTER TABLE ZA_POKLON_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_VILENJAK_ZA_POKLON_FK FOREIGN KEY (ID_Vilenjaka_za_poklone) REFERENCES VILENJAK_ZA_POKLON(ID) ENABLE;
	ALTER TABLE ZA_POKLON_POSEDUJE_VESTINU ADD CONSTRAINT VESTINA_OKLON_UNIQUE UNIQUE (ID_Vilenjaka_za_poklone, ID_Vestine) ENABLE;

	ALTER TABLE DETE_RODITELJ ADD CONSTRAINTS DETE_RODITELJ_FK FOREIGN KEY (ID_Deteta) REFERENCES DETE(ID) ENABLE;

--KREIRANJE TRIGERA
	CREATE OR REPLACE TRIGGER DETE_PK_AUTO
		BEFORE INSERT
		ON DETE
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT DETE_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER DETE_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER PISMO_PK_AUTO
		BEFORE INSERT
		ON PISMO
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT PISMO_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER PISMO_PK_AUTO ENABLE;
	

	
	CREATE OR REPLACE TRIGGER LISTA_ZELJA_PK_AUTO
		BEFORE INSERT
		ON LISTA_ZELJA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT LISTA_ZELJA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER LISTA_ZELJA_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER IGRACKA_PK_AUTO
		BEFORE INSERT
		ON IGRACKA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT IGRACKA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER IGRACKA_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER PESMA_PK_AUTO
		BEFORE INSERT
		ON PESMA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT PESMA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER PESMA_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER TIM_PK_AUTO
		BEFORE INSERT
		ON TIM
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT TIM_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER TIM_PK_AUTO ENABLE;
	
	CREATE OR REPLACE TRIGGER POKLON_PK_AUTO
		BEFORE INSERT
		ON POKLON
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT POKLON_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER POKLON_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER TOVAR_PK_AUTO
		BEFORE INSERT
		ON TOVAR
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT TOVAR_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER TOVAR_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER IRVAS_PK_AUTO
		BEFORE INSERT
		ON IRVAS
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT IRVAS_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER IRVAS_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER DEO_RADIONICE_PK_AUTO
		BEFORE INSERT
		ON DEO_RADIONICE
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT DEO_RADIONICE_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER DEO_RADIONICE_PK_AUTO ENABLE;
	
	CREATE OR REPLACE TRIGGER MAGICNA_VESTINA_PK_AUTO
		BEFORE INSERT
		ON MAGICNA_VESTINA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT MAGICNA_VESTINA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER MAGICNA_VESTINA_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER ZA_IRVASE_PK_AUTO
		BEFORE INSERT
		ON VILENJAK_ZA_IRVASE
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT VILENJAK_ZA_IRVASE_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER ZA_IRVASE_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER ZA_ISPORUKU_PK_AUTO
		BEFORE INSERT
		ON VILENJAK_ZA_ISPORUKU_POKLONA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT VILENJAK_ZA_ISPORUKU_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER ZA_ISPORUKU_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER ZA_IGRACKE_PK_AUTO
		BEFORE INSERT
		ON VILENJAK_ZA_IZRADU_IGRACAKA
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT VILENJAK_ZA_IGRACKE_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER ZA_IGRACKE_PK_AUTO ENABLE;
	
	
	CREATE OR REPLACE TRIGGER ZA_POKLON_PK_AUTO
		BEFORE INSERT
		ON VILENJAK_ZA_POKLON
		REFERENCING NEW AS NEW
		FOR EACH ROW
	BEGIN
		SELECT VILENJAK_ZA_POKLON_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
	/
	ALTER TRIGGER ZA_POKLON_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER IRVAS_TOVAR_PK_AUTO
		 BEFORE INSERT
		 ON IRVAS_ISPORUCUJE_TOVAR
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT IRVAS_TOVAR_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER IRVAS_TOVAR_PK_AUTO ENABLE;
	
	
	 CREATE OR REPLACE TRIGGER PAKOVANJE_POKLONA_PK_AUTO
		 BEFORE INSERT
		 ON PAKOVANJE_POKLONA
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT PAKOVANJE_POKLONA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER PAKOVANJE_POKLONA_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER ZA_IRVASE_VESTINA_PK_AUTO
		 BEFORE INSERT
		 ON ZA_IRVASE_POSEDUJE_VESTINU
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT ZA_IRVASE_VESTINA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER ZA_IRVASE_VESTINA_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER ZA_ISPOR_VESTINA_PK_AUTO
		 BEFORE INSERT
		 ON ZA_ISPORUKU_POSEDUJE_VESTINU
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT ZA_ISPORUKU_VESTINA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER ZA_ISPOR_VESTINA_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER ZA_IGRACKE_VESTINA_PK_AUTO
		 BEFORE INSERT
		 ON ZA_IGRACKE_POSEDUJE_VESTINU
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT ZA_IGRACKE_VESTINA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER ZA_IGRACKE_VESTINA_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER ZA_POKLON_VESTINA_PK_AUTO
		 BEFORE INSERT
		 ON ZA_POKLON_POSEDUJE_VESTINU
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT ZA_POKLON_VESTINA_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER ZA_POKLON_VESTINA_PK_AUTO ENABLE;
	
	 CREATE OR REPLACE TRIGGER DETE_RODITELJ_PK_AUTO
		 BEFORE INSERT
		 ON DETE_RODITELJ
		 REFERENCING NEW AS NEW
		 FOR EACH ROW
	 BEGIN
		 SELECT DETE_RODITELJ_PK_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
	 END;
	 /
	 ALTER TRIGGER DETE_RODITELJ_PK_AUTO ENABLE;
	

	
	
	
	


